# Generated by Django 4.2.4 on 2025-06-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadaccountstatus",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="leadaccountstatus",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="leadaccountstatus",
            name="payment_ss",
        ),
        migrations.AddField(
            model_name="lead",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leadsalestatus",
            name="payment_ss",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="followUpDate",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
