# Generated by Django 4.2.4 on 2025-06-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_api", "0002_remove_leadaccountstatus_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadsalestatus",
            name="discount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leadsalestatus",
            name="discount_ss",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
