# Generated by Django 5.2.3 on 2025-06-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_api", "0003_leadsalestatus_discount_leadsalestatus_discount_ss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsalestatus",
            name="status",
            field=models.CharField(max_length=20),
        ),
    ]
