# Generated by Django 5.2.3 on 2025-06-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_api", "0004_alter_leadsalestatus_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsalestatus",
            name="status",
            field=models.CharField(default="interested", max_length=20),
        ),
    ]
