# Generated by Django 5.2.3 on 2025-06-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_api", "0005_alter_leadsalestatus_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="followUpDate",
        ),
        migrations.AddField(
            model_name="leadsalestatus",
            name="followUpDate",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
