# Generated by Django 5.2.3 on 2025-06-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_api", "0006_remove_lead_followupdate_leadsalestatus_followupdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="comment",
        ),
        migrations.AddField(
            model_name="leadsalestatus",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
