# Generated by Django 5.2.3 on 2025-06-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_api", "0007_remove_lead_comment_leadsalestatus_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadboardscore",
            name="english_score",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="leadboardscore",
            name="pcm_score",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
