# Generated by Django 5.2.3 on 2025-07-01 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_api", "0008_alter_leadboardscore_english_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leadoperationstatus",
            old_name="registered_on_group",
            new_name="registered_on_app",
        ),
    ]
