# Generated by Django 5.2.3 on 2025-07-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "admin_api",
            "0009_rename_registered_on_group_leadoperationstatus_registered_on_app",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="leadsalestatus",
            name="recieved_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
