# Generated by Django 5.2.3 on 2026-04-06 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_api", "0010_leadsalestatus_recieved_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="book_price",
            field=models.IntegerField(
                error_messages={"invalid": "Book price must be a valid number."}
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="name",
            field=models.CharField(
                error_messages={
                    "max_length": "Batch name cannot be longer than 50 characters."
                },
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="price",
            field=models.IntegerField(
                error_messages={"invalid": "Price must be a valid number."}
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="status",
            field=models.CharField(
                default="active",
                error_messages={
                    "max_length": "Status cannot be longer than 20 characters."
                },
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                error_messages={"invalid": "Please select a valid user."},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="contact_number",
            field=models.CharField(
                error_messages={
                    "max_length": "Contact number cannot be longer than 20 characters.",
                    "unique": "A lead with this contact number already exists.",
                },
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="name",
            field=models.CharField(
                error_messages={
                    "max_length": "Name cannot be longer than 72 characters."
                },
                max_length=72,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                default="direct",
                error_messages={
                    "max_length": "Source cannot be longer than 20 characters."
                },
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                default="new",
                error_messages={
                    "max_length": "Status cannot be longer than 20 characters."
                },
                max_length=20,
            ),
        ),
    ]
