# Generated by Django 5.2.3 on 2026-04-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0003_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(default="sales", max_length=23),
        ),
    ]
