# Generated by Django 5.2.3 on 2026-04-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_api", "0005_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact",
            field=models.CharField(
                error_messages={
                    "max_length": "Contact number cannot be longer than 20 characters."
                },
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "A user with this email address already exists."
                },
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                error_messages={
                    "max_length": "Name cannot be longer than 72 characters."
                },
                max_length=72,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                default="sales",
                error_messages={
                    "max_length": "User type cannot be longer than 23 characters."
                },
                max_length=23,
            ),
        ),
    ]
